<<<<<<< HEAD
# yazi.toml
[manager]
ratio          = [ 2, 2, 4 ]
show_hidden = true
sort_dir_first = true
sort_by        = "alphabetical"
linemode = "size"
[preview]
wrap = "yes"
=======
# yazi.toml
[manager]
ratio          = [ 2, 2, 4 ]
show_hidden = true
sort_dir_first = true
sort_by        = "alphabetical"
linemode = "size"
[preview]
wrap = "yes"
>>>>>>> 7e202bf651b3b9887fe5f046fb7ecf4f6784e038
